name = "Lecture3"
uuid = "9dc84d5b-2aa2-4b03-bcee-e741e91c6f58"
authors = ["VincenzoGanci <nuccio.ganci@outlook.it>"]
version = "0.1.0"

[deps]
DynamicalSystems = "61744808-ddfa-5f27-97ff-6e42cc95d634"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
DynamicalSystems = "3.4.0"
OrdinaryDiffEq = "6.90.1"
Plots = "1.40.9"
