name = "Lecture2"
uuid = "538c7de7-cd5b-492d-8b6a-dae8f4ae65f8"
authors = ["VincenzoGanci <nuccio.ganci@outlook.it>"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
DifferentialEquations = "7.9.0"
Plots = "1.40.8"
