name = "Lecture1"
uuid = "1411ca2b-d79b-4279-b7e0-eae1e7a8ceb7"
authors = ["VincenzoGanci <nuccio.ganci@outlook.it>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Plots = "1.40.8"
