name = "Lecture1"
uuid = "e1d97c28-b24b-4dda-8aed-f1ee92bb9de9"
authors = ["VincenzoGanci <nuccio.ganci@outlook.it>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Plots = "1.40.8"
