name = "Lecture1"
uuid = "b6f31966-d947-46af-97b3-924b0f45547f"
authors = ["VincenzoGanci <nuccio.ganci@outlook.it>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Plots = "1.40.8"
